import PDFDocument from 'pdfkit';
import { Inspection } from '../db/database';

export class ReportGenerator {
  public static async generatePdf(inspection: Inspection): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 40,
        info: {
          Title: `Inspection Report - ${inspection.inspectionNumber}`,
          Author: 'LabelGuard India - Legal Metrology Compliance Platform',
          Subject: 'Preliminary Compliance Screening Record',
          Keywords: 'Legal Metrology, Packaged Commodities, SIH2026'
        }
      });

      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      // 1. Header Banner
      doc
        .rect(40, 40, 515, 65)
        .fill('#0f172a');

      doc
        .fontSize(11)
        .font('Helvetica-Bold')
        .fillColor('#f8fafc')
        .text('GOVERNMENT OF INDIA', 50, 50, { align: 'center', width: 495 })
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#94a3b8')
        .text('MINISTRY OF CONSUMER AFFAIRS, FOOD & PUBLIC DISTRIBUTION', 50, 65, { align: 'center', width: 495 })
        .fontSize(12)
        .font('Helvetica-Bold')
        .fillColor('#38bdf8')
        .text('LEGAL METROLOGY PRELIMINARY INSPECTION RECORD', 50, 80, { align: 'center', width: 495 });

      // 2. Metadata Box
      doc.y = 115;
      doc
        .rect(40, 115, 515, 80)
        .fill('#f8fafc')
        .stroke('#cbd5e1');

      doc.fillColor('#0f172a').fontSize(9);

      // Left Column
      doc
        .font('Helvetica-Bold').text('Inspection ID:', 50, 125)
        .font('Helvetica').text(inspection.inspectionNumber, 140, 125)
        .font('Helvetica-Bold').text('Date & Time:', 50, 140)
        .font('Helvetica').text(new Date(inspection.timestamp).toLocaleString('en-IN'), 140, 140)
        .font('Helvetica-Bold').text('Rule Version:', 50, 155)
        .font('Helvetica').text(inspection.ruleVersionCode, 140, 155)
        .font('Helvetica-Bold').text('Location:', 50, 170)
        .font('Helvetica').text(
          inspection.latitude && inspection.longitude
            ? `Lat: ${inspection.latitude.toFixed(4)}, Long: ${inspection.longitude.toFixed(4)}`
            : (inspection.storeAddress || 'Field Inspection Site'),
          140,
          170
        );

      // Right Column: Status Banner
      const statusColor = 
        inspection.overallAssessment === 'APPEARS_COMPLIANT' ? '#16a34a' :
        inspection.overallAssessment === 'NEEDS_VERIFICATION' ? '#d97706' : '#dc2626';

      const statusText =
        inspection.overallAssessment === 'APPEARS_COMPLIANT' ? 'APPEARS COMPLIANT' :
        inspection.overallAssessment === 'NEEDS_VERIFICATION' ? 'NEEDS VERIFICATION' : 'POTENTIAL ISSUE DETECTED';

      doc
        .rect(340, 125, 200, 32)
        .fill(statusColor);

      doc
        .fontSize(10)
        .font('Helvetica-Bold')
        .fillColor('#ffffff')
        .text(statusText, 340, 136, { align: 'center', width: 200 });

      doc
        .fontSize(8)
        .font('Helvetica')
        .fillColor('#64748b')
        .text('Generated by LabelGuard India Platform', 340, 168, { align: 'center', width: 200 });

      // 3. Product Particulars
      doc.y = 210;
      doc
        .fontSize(11)
        .font('Helvetica-Bold')
        .fillColor('#0f172a')
        .text('1. COMMODITY PARTICULARS');

      doc
        .rect(40, doc.y + 4, 515, 65)
        .fill('#ffffff')
        .stroke('#e2e8f0');

      const pY = doc.y + 12;
      doc.fontSize(9);
      doc
        .font('Helvetica-Bold').text('Product Name:', 50, pY)
        .font('Helvetica').text(inspection.productName, 140, pY)
        .font('Helvetica-Bold').text('Category:', 50, pY + 16)
        .font('Helvetica').text(inspection.categoryName, 140, pY + 16)
        .font('Helvetica-Bold').text('Manufacturer:', 50, pY + 32)
        .font('Helvetica').text(inspection.manufacturerName || 'Extracted on label', 140, pY + 32);

      // 4. Compliance Checklist Table
      doc.y = 295;
      doc
        .fontSize(11)
        .font('Helvetica-Bold')
        .fillColor('#0f172a')
        .text('2. STATUTORY DECLARATION COMPLIANCE EVALUATION');

      let tableY = doc.y + 6;

      // Table Header
      doc
        .rect(40, tableY, 515, 20)
        .fill('#e2e8f0');

      doc
        .fontSize(8)
        .font('Helvetica-Bold')
        .fillColor('#1e293b')
        .text('RULE CLAUSE', 45, tableY + 6, { width: 75 })
        .text('REQUIREMENT TITLE', 125, tableY + 6, { width: 170 })
        .text('RESULT', 300, tableY + 6, { width: 85 })
        .text('DETAILS / SUMMARY', 390, tableY + 6, { width: 160 });

      tableY += 22;

      for (const check of inspection.complianceChecks.slice(0, 9)) {
        const rowBg = check.result === 'FAIL' ? '#fef2f2' : check.result === 'REVIEW' ? '#fffbeb' : '#ffffff';
        doc.rect(40, tableY, 515, 20).fill(rowBg).stroke('#f1f5f9');

        const badgeColor = 
          check.result === 'PASS' ? '#15803d' :
          check.result === 'FAIL' ? '#b91c1c' :
          check.result === 'REVIEW' ? '#b45309' : '#64748b';

        doc
          .fontSize(8)
          .font('Helvetica-Bold')
          .fillColor('#334155')
          .text(check.ruleClause, 45, tableY + 5, { width: 75 })
          .font('Helvetica')
          .text(check.summary.substring(0, 32) + (check.summary.length > 32 ? '...' : ''), 125, tableY + 5, { width: 170 })
          .font('Helvetica-Bold')
          .fillColor(badgeColor)
          .text(check.result, 300, tableY + 5, { width: 85 })
          .font('Helvetica')
          .fillColor('#475569')
          .text(check.details ? check.details.substring(0, 38) + '...' : '-', 390, tableY + 5, { width: 160 });

        tableY += 21;
      }

      // 5. Conflicts / Evidence Section
      if (inspection.conflicts && inspection.conflicts.length > 0) {
        doc.y = tableY + 10;
        doc
          .fontSize(11)
          .font('Helvetica-Bold')
          .fillColor('#dc2626')
          .text('3. DETECTED CROSS-FACE INCONSISTENCY');

        for (const conflict of inspection.conflicts) {
          doc.y += 4;
          doc
            .rect(40, doc.y, 515, 36)
            .fill('#fef2f2')
            .stroke('#fca5a5');

          doc
            .fontSize(8)
            .font('Helvetica-Bold')
            .fillColor('#991b1b')
            .text(`CONFLICT: ${conflict.fieldKey.toUpperCase()}`, 50, doc.y + 6)
            .font('Helvetica')
            .text(conflict.description, 50, doc.y + 18, { width: 495 });

          doc.y += 42;
        }
      }

      // 6. Inspector Verification Decision
      const verY = Math.max(doc.y + 15, 570);
      doc
        .rect(40, verY, 515, 60)
        .fill('#f8fafc')
        .stroke('#cbd5e1');

      doc
        .fontSize(9)
        .font('Helvetica-Bold')
        .fillColor('#0f172a')
        .text('4. INSPECTOR HUMAN VERIFICATION & SIGN-OFF', 50, verY + 8)
        .font('Helvetica')
        .text(`Recorded Decision: ${inspection.verification?.decision || 'PENDING FIELD SIGN-OFF'}`, 50, verY + 24)
        .text(`Inspector: ${inspection.verification?.inspectorName || 'Ramesh Sharma (LM-DEL-2024-88)'}`, 50, verY + 38)
        .text(`Notes: ${inspection.verification?.inspectorNotes || 'Physical inspection verified with evidence annotations.'}`, 280, verY + 24, { width: 260 });

      // 7. Statutory Prototype Disclaimer Footer
      doc
        .fontSize(7)
        .font('Helvetica-Oblique')
        .fillColor('#94a3b8')
        .text(
          'STATUTORY NOTICE: This report is a computer-assisted preliminary screening record generated for inspection verification under the Legal Metrology (Packaged Commodities) Rules, 2011. It does not constitute an authoritative judicial conviction without formal seizure panchnama executed by an authorized Legal Metrology Officer.',
          40,
          770,
          { align: 'center', width: 515 }
        );

      doc.end();
    });
  }
}
